version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  # Add ecosystem-specific entries below, for example:
  # - package-ecosystem: npm
  #   directory: "/"
  #   schedule:
  #     interval: weekly