---
# Label pull requests based on the paths of changed files.
# See: https://github.com/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

# Add project-specific labels below, for example:
# source:
#   - changed-files:
#       - any-glob-to-any-file:
#           - "src/**"
